---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.2'
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[audit_test::default]
      - recipe[audit_test::breakit]
      - recipe[audit_test::checkit]
    attributes:

